import { assets, collections, events, graph, papers, repos, tools, topics } from "./loaders";
import { ontology } from "./ontology";

/**
 * The published endpoints, in one place.
 *
 * Both /api/index.json (the machine-readable directory) and /api (the documentation page)
 * read this list, so a new endpoint cannot appear in one and be missing from the other, and
 * the counts on the page are the counts the files actually contain.
 */
export interface ApiEndpoint {
  path: string;
  entity: string;
  description: string;
  /** The payload itself, so the page can count it, size it and sample it at build time. */
  items: unknown[];
}

export const endpoints: ApiEndpoint[] = [
  {
    path: "/api/papers.json",
    entity: "Paper",
    description:
      "Every build in the corpus: cost, licence, repository status, rubric scores and which performance values the paper reports.",
    items: papers
  },
  {
    path: "/api/tools.json",
    entity: "Tool",
    description: "Named instruments, aggregated across the papers that describe them.",
    items: tools
  },
  {
    path: "/api/repos.json",
    entity: "Repo",
    description:
      "Repositories and deposits linked from the corpus, with the date each was last checked for reachability.",
    items: repos
  },
  {
    path: "/api/topics.json",
    entity: "Topic",
    description: "Application areas used to group the corpus.",
    items: topics
  },
  {
    path: "/api/assets.json",
    entity: "Asset",
    description:
      "Build artifacts — CAD, bills of materials, firmware, protocols — with provenanceSource recording whether a curator or an extractor found each one.",
    items: assets
  },
  {
    path: "/api/events.json",
    entity: "Event",
    description: "Venues and workshops associated with a record.",
    items: events
  },
  {
    path: "/api/collections.json",
    entity: "Collection",
    description: "Curated lenses over the corpus.",
    items: collections
  },
  {
    path: "/api/graph.json",
    entity: "Graph",
    description:
      "Nodes and edges linking papers, tools, repositories, topics and assets. Edges carry an explicit relation.",
    items: graph.nodes
  },
  {
    path: "/api/ontology.json",
    entity: "Ontology",
    description: "The schema itself: entity names, key fields and the relation vocabulary.",
    items: ontology.entities
  }
];

/**
 * Plain-language notes for the fields a downstream user is most likely to misread.
 *
 * Only fields where the name alone is misleading are listed: what an empty string means,
 * which values are computed rather than recorded, where a single field holds several values.
 * The field tables on /api are generated by walking a real record, so anything not described
 * here still appears, just without a note.
 */
export const FIELD_NOTES: Record<string, string> = {
  id: "Stable within a build of the site; regenerated when the corpus is rebuilt. Cite by doi or slug instead.",
  slug: "URL segment for the record's page on this site.",
  doi: "May hold several DOIs separated by ' | ' where a record has both a preprint and a version of record.",
  year: "Publication year. Present for all 60 records.",
  category: "Application areas. A record can belong to more than one.",
  modality: "Fabrication or handling modality. Overlaps category and is not case-normalised against it.",
  systemOrTechnology: "The instrument's own name, where the paper gives one. ' | ' separates alternatives.",
  approximateCost:
    "Free text exactly as the paper states it: '230', '<$1,500', '3000-7000', '141 USD + 3D Printer'. Eleven records state no currency. Empty means no cost was stated.",
  approximateCostSource: "Which workbook the cost came from, when it was not in the curated sheet.",
  artifactLicence:
    "Licence governing the design files, not the article. value is empty when none was found; source records where it was found.",
  repo: "Null when no repository link resolved. accessibility.maintenance is active | aging | stale | unknown, derived from the last commit date at checkedAt.",
  textRepoLinks:
    "Repository URLs mined from the full text but not verified. Weaker evidence than repo, stronger than nothing.",
  assetTypes: "Kinds of build file found for this record: cad, bom, software, firmware, documentation, protocol, schematics, pcb.",
  criteriaAssessment:
    "Rubric scores. criteria[].display is false for the two criteria that cannot separate one build from another; observedMin/observedMax give the range the corpus actually uses, which is narrower than 1-5.",
  reportedMetrics:
    "Whether the paper states a number for each performance requirement. status is yes | no | na; na means the full text is not held, so the question is unanswered rather than answered no.",
  derived: "Computed by the build from the fields above, not recorded by a curator.",
  publication: "Crossref and OpenAlex metadata. matchMethod is 'doi' when the DOI was confirmed, and abstract is present for all 60 records.",
  provenanceSource: "curated when a person recorded it, heuristic when an extractor did.",
  relation: "Edge type. One of the values listed under Graph and ontology."
};
